server:
  port: 9090
  servlet:
    context-path: /booking
spring:
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: sbookingtech.info@gmail.com
    password: emuydbkydncdzund
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 60000
          timeout: 60000
          writetimeout: 60000
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

rsa:
  private-key: "classpath:certs/private.pem"
  public-key: "classpath:certs/public.pem"
application:
  drivers:
    geckoDriverPath: /Users/ercanemirleroglu/Documents/Projects/drivers/geckodriver
    chromeDriverPath: /Users/ercanemirleroglu/Documents/Projects/drivers/chromedriver
  commands:
    killCompletely: false
  automation:
    path: "https://www.booking.com/"
    pageLoadTimeout: 240
    implicitlyWait: 60
    setScriptTimeout: 60
    closeRegisterModalEvent: true