server:
  port: 9090
spring:
  datasource:
    url: "jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}"
    driverClassName: org.postgresql.Driver
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    user:
      password: ${PROD_DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

application:
  drivers:
    geckoDriverPath: /usr/local/bin/geckodriver
    chromeDriverPath: /usr/local/bin/chromedriver
