server:
  port: 9090
spring:
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    user:
      password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

application:
  drivers:
    geckoDriverPath: /Users/ercanemirleroglu/Documents/Projects/drivers/geckodriver
