server:
  port: 9090
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/booking"
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    user:
      password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

jwt:
  secret: ercanemirleroglu
